### ISSUE TITLE
open-source the code of analysis

### ISSUE THREAD

**Issue by JewelChen2019** [lucaro/V3C2Analysis#1]
Hi, Dr. Luca Rossetto
After reading your paper _**Insights on the {V3C2} Dataset}**_, I found that your analysis of V3C datasets is very comprehensive and exciting. Recently, I crawled some video datasets on the Internet as a self-developed dataset. I hope to use your analysis tools which analyze the V3C to analyze the datasets I crawled. If possible, could you please open-source the code of analysis?

**Comment by lucaro** [comment]
Hey,

thanks for your interest in the dataset. The code of this analysis is already largely available publicly. There are python scripts for the OCR and the extraction of the deep features in this repository. The ASR is generated with DeepSpeech (https://github.com/mozilla/DeepSpeech) and the color labels have been generated using Cineast (https://github.com/vitrivr/cineast). The rest was of a rather ad-hoc interactive nature, but should be reasonably straight forward. Best of luck with your analysis.
